### ISSUE TITLE
邀请函

### ISSUE THREAD

**Issue by CSDAIZUO** [shizhilvren/os_fat32#1]
看到你的github repo，我印象深刻。
现邀请你 150rmb/h 开发跨平台单机逻辑计算系统 
时间为一学期
涉及到C语言网络编程 前端用python搭建框架
有兴趣可联系我了解项目需求 谢谢

**Comment by shizhilvren** [comment]
谢谢你的邀请，可以留一下联系方式么，我希望详细了解一下。

**Comment by CSDAIZUO** [comment]
加你啦
